---
title: 'Data607 Discussion 12: Recommender Systems'
author: "Ritesh Lohiya"
date: "April 18, 2018"
output: html_document
---

Your task is to analyze an existing recommender system that you find interesting. You should: 

Perform a Scenario Design analysis as described below. Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization's customers.
Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.
Include specific recommendations about how to improve the site's recommendation capabilities going forward. 
Create your report using an R Markdown file, and create a discussion thread with a link to the GitHub repo where your Markdown file notebook resides. You are not expected to need to write code for this discussion assignment.
 
I will consider the recommender system for Coupon deal company GROUPON.

GROUPON: Groupon is an American worldwide e-commerce marketplace connecting subscribers with local merchants by offering activities, travel, goods and services in 15 countries.

#What are the target users? 

Answer: Groupon subscribers across 15 countries. Around 35 million subscribers.

#What are their key goals? 

Answer: Connecting subscribers with local merchants by offering activities, travel, goods and services by providing personalized recommendations on deals.

#How can I help them accomplish their goals? 

Answer: By building an algorithm for collaborative filtering and content based filtering so that subscribers will be more interseted in the deals.

Would doing a scenario design for apple make sense? No as GROUPON targets a wide range of population with different needs and interests.

#Reverse Engineer:

Apriori algorithm: Association Rules between Keywords.Traditional Apriori algorithm looks at association rules between deals, e.g., beer and dippers are usually purchased together 

Recommendation by Quantity Sold: Efficient recommendation method used by e-commerce websites is to just sort all deals by quantity of coupons sold. 

#Specific recommendations for improvements

We can build simple ranking algorithm that could use various type of information available in order to come with a useful ranking system that could recommend the best deals for each of our customers. This would help to make the recommendations more accurate.